chore(license): update LICENSE and README.md
unicode-org/unicodetools pull request #521
Opened 2023-08-15 23:42 UTC by srl295

https://github.com/unicode-org/.github/issues/6

2023-08-16 00:06 UTC, annebright commented
Looks good except I don't think we need/want the reference to Maven in the ReadMe. Otherwise fine.

2023-08-16 00:08 UTC, srl295 commented
fixed

2023-08-17 23:51 UTC, annebright submitted a review, later dismissed

2023-08-18 21:36 UTC, srl295 commented on LICENSE
> +UNICODE LICENSE V3
@annebright  it did get changed ^

2023-08-18 21:37 UTC, srl295 commented
> License title did not get changed to new UNICODE LICENSE V3. Also, I did not designate this repo to get the reference to Maven, but do you know something that I do not that suggests we need the Maven reference?

- It did get changed
- The maven reference was an error and was fixed 3 days ago.

2023-08-18 22:14 UTC, annebright requested changes
The Maven reference seems to still be there in the ReadMe notice

2023-08-18 22:17 UTC, srl295 commented
> The Maven reference seems to still be there in the ReadMe notice

I'm not seeing it. If you go to the Files Changed tab this is what it shows me.  

<img width="1381" alt="image" src="https://github.com/unicode-org/unicodetools/assets/855219/cfaba9ff-04f1-45f1-94cf-9648c8c45289">

What's the exact URL where you're seeing the maven notice?

2023-08-18 22:18 UTC, markusicu commented
> > The Maven reference seems to still be there in the ReadMe notice
> 
> I'm not seeing it.

me neither

2023-08-18 22:28 UTC, annebright approved these changes
Well now I am not seeing it either, so approved.

2023-08-21 16:47 UTC, merged