Fix InSC of U+16D43 KIRAT RAI LETTER A to Vowel_Independent
unicode-org/unicodetools pull request #608
Opened 2023-11-14 01:29 UTC by roozbehp

The proposal doesn't request syllabic categories, but we decided to assign them. It looks like we overlooked that the first letter is an independent vowel, not a consonant.

2023-11-14 01:40 UTC, eggrobin commented
I think that was a conscious choice I made based on my understand of the proposal and by analogy to other scripts. Of course it is quite possible that I got that wrong, but I would like to take a closer look.

Ideally not while I am on vacation, I am trying to limit my Unicode work to cuneiform until I am back.

2023-11-14 17:17 UTC, Ken-Whistler approved these changes
I think the change is o.k. It reflects the explicit claim in the proposal. In any case, I've updated the subheads in the 16.0 names list draft to track this.

2023-11-14 19:27 UTC, markusicu commented
Robin requested that we wait until he has time to compare with his previous notes. Let's give him a few days.

2023-11-20 13:19 UTC, eggrobin requested changes
I gave it InSC=Consonant by analogy with U+11EF1 𑻱 MAKASAR LETTER A and others. However, we are inconsistent here.

L2/22-043R reads:
> There is a single vowel letter which functions as a vowel carrier. Other vowels are represented as dependent signs (see
Fig. 1, 5a, 6, 7, 10). Independent forms of other vowels are produced by writing those vowels with this letter.

This is the same as for Makasar, on which the Standard reads:
> There is only one independent vowel sign, U+11EF1 𑻱 MAKASAR LETTER A. Vowel signs
can be attached to this character to produce other vowel sounds when a syllable has no
consonant, such as at the beginning of a word.

Or for Ahom:
> Ahom has no independent vowels, but instead uses U+11712 AHOM LETTER A followed by the corresponding dependent vowel sign (or signs).

However, other scripts do the same thing and have their A as an Independent_Vowel instead:
> The vowel _a_ is represented by U+11A50 SOYOMBO LETTER A.
When it occurs with a vowel sign, SOYOMBO LETTER A serves as a vowel-carrier, indicating
an independent vowel.

> The Zanabazar Square script has one vowel letter, nine dependent vowel marks, and one vowel length mark. The letter a vowel, U+11A00 ZANABAZAR SQUARE LETTER A, has the value /a/ when it occurs independently. It can also assume the
value of a combined vowel sign.

It sounds like we should decide what we want to do for those kinds of As, fix the ones that do the other thing (that will need a UTC decision, likely based on a PAG recommendation), and improve the documentation of InSC to mention that.

2023-11-20 13:25 UTC, eggrobin commented
Filed https://github.com/unicode-org/properties/issues/203, let’s discuss it there.

2024-05-02 00:38 UTC, markusicu commented
Is this still waiting on getting https://github.com/unicode-org/properties/issues/203 resolved?

2024-05-02 00:39 UTC, eggrobin commented
I think so.

2024-07-29 21:01 UTC, markusicu commented
FYI, pending change still waiting for resolution of https://github.com/unicode-org/properties/issues/203 which got punted beyond Unicode 16.

2024-11-08 21:24 UTC, eggrobin commented
We are not doing this, instead UTC decided to
[UTC-181-C44] Consensus: Change the Indic_Syllabic_Category of U+11A50 SOYOMBO LETTER A and U+11A00 ZANABAZAR SQUARE LETTER A from Vowel_Independent to Consonant, and that of U+1900 LIMBU VOWEL-CARRIER LETTER from Consonant_Placeholder to Consonant, for Unicode 17.0 [Ref: 4.6 in L2/24-228]

I am therefore closing this PR.

2024-11-08 21:24 UTC, closed without merging