[WIP] Workflow to check we have a paper trail on pipeline changes
unicode-org/unicodetools pull request #629
Opened 2023-12-15 13:50 UTC by eggrobin

VERY WIP, I just need to have a PR to test the workflow.

See https://github.com/unicode-org/unicodetools/pull/626#issuecomment-1857485410.

2023-12-19 21:02 UTC, srl295 requested changes

2023-12-19 21:02 UTC, srl295 commented on .github/workflows/pipeline.yml
> +    if: needs.labels-for-repertoire-changes.outputs.pipeline-label != 'pipeline-16.0'
`16` should be a variable, perhaps a repo variable <https://github.com/unicode-org/unicodetools/settings/variables/actions>

2023-12-19 21:02 UTC, srl295 commented on .github/workflows/pipeline.yml
> +    if: needs.labels-for-repertoire-changes.outputs.pipeline-label != 'pipeline-16.0'
don't we have `16.0` somewhere?  The python script could discover this. Take the `if` out and analyze it within the python script

2023-12-19 21:02 UTC, srl295 commented on .github/workflows/pipeline.yml
> +        EOF
split into repo

2023-12-19 21:02 UTC, srl295 commented
looks like a good idea, with some suggestions…

2023-12-20 14:31 UTC, eggrobin commented on .github/workflows/pipeline.yml
> +        EOF
Split out the Python scripts, they are probably more readable that way than in a heredoc in a yaml string; but my experience with these workflow scripts is that they are hard to test, as the bugs tend to be bad assumptions as to what the JSON payload actually contains, which depends on the specific event triggering the workflow.

2023-12-20 20:51 UTC, eggrobin commented on .github/workflows/pipeline.yml
> +        fi
Added a comment, but I don’t think there is much to gain from splitting that regex into its own file.

2023-12-20 21:09 UTC, srl295 commented on .github/workflows/pipeline.yml
> +        fi
could be useful on its own… not a high prio

2023-12-20 21:09 UTC, srl295 approved these changes

2023-12-20 23:04 UTC, merged