Update docRegistry.txt to end of 2023
unicode-org/unicodetools pull request #655
Opened 2024-01-18 02:37 UTC by nedley

2024-01-18 02:38 UTC, nedley commented on unicodetools/src/main/resources/org/unicode/tools/emoji/docRegistry.txt
> +L2/23-178	Proposed Update UTS #51, Unicode Emoji (HTML version)	Mark David, Ned Holbrook	2023-07-10
LOL "Mark David"?

2024-01-18 04:12 UTC, macchiati requested changes
looks good except for those 2 lines.

2024-01-18 04:12 UTC, macchiati commented on unicodetools/src/main/resources/org/unicode/tools/emoji/docRegistry.txt
> +ABOVE	Lorna Evans	2023-05-15
Malformed line (tool should have caught it. (hmmm). Change the \n to space.

2024-01-18 04:12 UTC, macchiati commented on unicodetools/src/main/resources/org/unicode/tools/emoji/docRegistry.txt
> +name related to Mazu belief and customs to UAX #45	Eiso Chan	2023-10-08
Malformed line (tool should have caught it. (hmmm). Change the \n to space.

2024-01-19 00:52 UTC, macchiati approved these changes

2024-01-19 02:30 UTC, merged