Fix the IndexUnicodeProperties Joining_Type
unicode-org/unicodetools pull request #657
Opened 2024-01-18 09:53 UTC by eggrobin

DRAFT: failing test only.

2024-01-18 15:54 UTC, macchiati requested changes
clever approach. A few items:
The UcdProperty and UcdProperty values are generated by GenerateEnums, so that needs to be modified to produce the right values. Otherwise the next time it is run, the changes will be overridden.

Short term, I think making the derived property "occupy" field 1 is a clever hack. Longer term I think we need to add a better mechanism for derived IndexUnicodeProperties.

2024-01-18 16:37 UTC, eggrobin commented
> The UcdProperty and UcdProperty values are generated by GenerateEnums, so that needs to be modified to produce the right values. Otherwise the next time it is run, the changes will be overridden.

I ran GenerateEnums already (a CI check tests that it does not change anything).

> I think we need to add a better mechanism for derived IndexUnicodeProperties.

We have plenty of those in IndexUnicodeProperties.txt already, see e.g. https://github.com/unicode-org/unicodetools/blob/77e3ce601ff2970b1a9b8bc7cf5d9445fd4554e5/unicodetools/src/main/resources/org/unicode/props/IndexUnicodeProperties.txt#L124-L143

2024-01-18 16:40 UTC, eggrobin commented
> making the derived property "occupy" field 1 is a clever hack

You may have misread that line of IndexUnicodeProperties.txt, it is

**DerivedJoiningType**; Joining_Type; 1

that is, we are getting it from the derived file (like the other derived properties), where it actually does reside in field 1.

2024-01-18 16:43 UTC, macchiati approved these changes

2024-01-20 00:56 UTC, markusicu approved these changes

2024-01-20 00:59 UTC, merged