UTC-178-A13: jg long alias Teh_Marbuta_Goal
unicode-org/unicodetools pull request #676
Opened 2024-01-31 22:13 UTC by markusicu

UTC-178-A13 Action Item for Mark Davis, PAG: Make the proposed change to PropertyValueAliases.txt to fix the long value alias for jg=Teh_Marbuta_Goal. For Unicode 16.0. See L2/24-009 item 2.6.

2024-01-31 22:16 UTC, roozbehp submitted a review, later dismissed
LGTM

2024-01-31 22:18 UTC, Manishearth approved these changes

2024-01-31 22:22 UTC, Ken-Whistler requested changes
You should also update the copyright line to 2024, unless the intent is that gets handled by a separate PR on a group of files later. Otherwise the change for the jg alias looks fine.

2024-01-31 22:27 UTC, markusicu commented
> You should also update the copyright line to 2024, unless the intent is that gets handled by a separate PR on a group of files later.

Good catch, but we should do that in a separate change for all of the generated files.

2024-01-31 22:28 UTC, markusicu commented
@eggrobin @macchiati when I regenerate the UCD files, the intended change here is reverted :-( Why??

2024-01-31 22:47 UTC, Manishearth submitted a review, later dismissed

2024-01-31 23:05 UTC, eggrobin commented
> when I regenerate the UCD files, the intended change here is reverted :-( Why??

PVA is not a source file if I recall correctly, instead it is expelled from the guts of ToolUnicodePropertySource, UCD_Name, UCD_Types, and friends; but I cannot immediately spot the culprit there.

2024-01-31 23:10 UTC, eggrobin commented
My uneducated guess is that it comes from here:

https://github.com/unicode-org/unicodetools/blob/22efd1fe65d90df1b23d2eb0ee23f38fe0f3bbff/unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java#L1853-L1856

Which is used here:

https://github.com/unicode-org/unicodetools/blob/22efd1fe65d90df1b23d2eb0ee23f38fe0f3bbff/unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java#L2076-L2082

There may be a bug in `lookup` when the main = aux and aux2 is present.

2024-01-31 23:22 UTC, macchiati submitted a review, later dismissed

2024-01-31 23:37 UTC, eggrobin commented
Obviously pulling on that thread brings various bits of MakeUnicodeFiles crashing down.

I think I see how to fix that, I will push a commit to this branch tomorrow.

2024-01-31 23:41 UTC, macchiati commented
Hmmm. When you run GenerateEnums it should make the necessary changes in
the PVA data within the props directory. So if GenerateEnums was not run,
that could be the problem. On the other hand, the change to UCDProperties
seems to indicate that that was done.

On Wed, Jan 31, 2024 at 3:06 PM Robin Leroy ***@***.***>
wrote:

> when I regenerate the UCD files, the intended change here is reverted :-(
> Why??
>
> PVA is not a source file if I recall correctly, instead it is expelled
> from the guts of ToolUnicodePropertySource, UCD_Name, UCD_Types, and
> friends; but I cannot immediately spot the culprit there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/unicodetools/pull/676#issuecomment-1920142134>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJLEMCKKQKQYG7452EBPHDYRLE55AVCNFSM6AAAAABCT2SD3GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRQGE2DEMJTGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-01 00:04 UTC, eggrobin commented
> When you run GenerateEnums it should make the necessary changes in
the PVA data within the props directory. So if GenerateEnums was not run,
that could be the problem.

That is not how it works, neither PVA nor the generated UCDProperties are actually authoritative. The source of truth is the bad old ToolsUnicodePropertySource and UCD_Names, and MakeUnicodeFiles generates PVA based on that and nothing else.

This would be relatively straightforward to fix for Joining_Type, were it not for the fact that it exposes all of the grievous hackery around CCC between ToolUnicodePropertySource and MakeUnicodeFiles.

2024-02-01 00:18 UTC, markusicu commented
> My uneducated guess is that it comes from here

Thanks for the tip!
That code actually basically looks fine. The problem is that `lookup()` adds aliases using `UnicodeProperty.addUnique(some-alias, result);`

It faithfully adds the short name Teh_Marbuta_Goal, then the long name Teh_Marbuta_Goal, then the alias Hamza_On_Heh_Goal. But *because it "adds unique" aliases, it drops the long name*.

2024-02-01 00:19 UTC, eggrobin commented
> It faithfully adds the short name Teh_Marbuta_Goal, then the long name Teh_Marbuta_Goal, then the alias Hamza_On_Heh_Goal. But because it "adds unique" aliases, it drops the long name.

Yes, and removing the uniques fixes that. But then CCC gets all messed up when you regenerate the UCD. (and DT, but that one is an easy fix.)

2024-02-01 00:42 UTC, eggrobin commented
𒌝𒈠 𒀀𒈾𒆪𒈠
> I will push a commit to this branch tomorrow (or rather today, my time zone).

Done; and with that I will get back to those Akkadian exercises I was working on…

2024-02-01 00:43 UTC, eggrobin approved these changes
Approving so things do not get blocked, but to be honest I am approving my own code here, so someone else should really look at this.

2024-02-01 00:44 UTC, markusicu commented
> Done

Thank you very much!!
I was trying to always add the long name to the list, but ran into the ccc and dt problems -- and tried to hack around those.
Your fix reduces the hackery, so that's much better!

Anyone else opposed?

2024-02-01 01:20 UTC, merged