publish the UCD.zip in alpha & beta as well
unicode-org/unicodetools pull request #694
Opened 2024-02-09 20:11 UTC by markusicu

by user demand since popular web browsers no longer support FTP

2024-02-09 20:41 UTC, rickmcgowan approved these changes

2024-02-09 21:45 UTC, Ken-Whistler requested changes
Changes here seem o.k., but somehow there is a recursion error in what was zipped and delivered for deployment. I'm not sure if that is somewhere in these scripts or outside of them. Please clarify and fix.

2024-02-09 22:41 UTC, markusicu commented
> Changes here seem o.k., but somehow there is a recursion error in what was zipped and delivered for deployment. I'm not sure if that is somewhere in these scripts or outside of them. Please clarify and fix.

Pretty much outside. The script deletes "alpha.zip" but I had renamed the previous version for posting and failed to delete that. I re-ran the script and re-posted uni16-alpha-20240209.zip.

2024-02-10 03:02 UTC, Ken-Whistler approved these changes

2024-02-12 16:26 UTC, merged