Remove SegmenterCldr.txt
unicode-org/unicodetools pull request #947
Opened 2024-10-09 15:40 UTC by eggrobin

Back [in March](https://github.com/unicode-org/unicodetools/issues/492#issuecomment-2023947121) I had written:
> Right now the 15.1 line breaking rules in SegmenterCldr.txt are used by no-one, and this is a good thing since they are wrong and untested (and we went through a release with these wrong rules!). Let’s get rid of that quasi-copy before someone gets hurt.

And then I forgot to do anything. They are still wrong, and they have not been updated for 16.0. Let’s get rid of those.

2024-10-09 19:09 UTC, macchiati submitted a review, later dismissed

2024-10-11 19:45 UTC, macchiati requested changes
I'm not sure we should remove the whole mechanism, because we may need it back in the future. Once we settle on overrides with "character x behaves like character y", I'd be comfortable removing.

2024-10-11 19:56 UTC, eggrobin commented
We discussed that earlier: https://github.com/unicode-org/unicodetools/issues/492#issuecomment-2024020481.
Right now this is not used, and if it had been used it would have produced garbage, most likely without anyone noticing, so it is a footgun: we really should remove SegmenterCldr.txt before someone gets hurt.
When it comes to the code itself, I am removing the minimum needed to make CI pass; if we ever want to bring back a SegmenterCldr this is trivial to revert (that is why we have source control!).

2024-10-11 23:49 UTC, macchiati approved these changes
Ok makes sense

2024-10-14 11:26 UTC, merged